### ISSUE TITLE
Request for Open-Source Release

### ISSUE THREAD

**Issue by heiyumiao** [WangY18/ManifoldInterceptMethod#1]
Dear Up,

First, congratulations on your paper’s acceptance! I have been following your work on the Manifold-Intercept Method (MIM) with great interest. It’s clear that MIM has significant potential, especially in solving third- and fourth-order trajectory planning problems with impressive efficiency and accuracy.

As your paper is now officially accepted, I’m eagerly looking forward to the release of the open-source code for MIM, which I believe would be immensely beneficial for further understanding and application in various projects.

Thank you again for your outstanding contributions. I look forward to seeing your future developments.

Best regards,

**Comment by WangY18** [comment]
Dear heiyumiao,

I sincerely appreciate you for your interest in our MIM. I am planning to reorganize the MIM's project and make it open-source in the near future. Given that the current version of MIM contains some instances of hard coding, it is necessary for us to rewrite the code for higher numerical stability. If all proceeds as anticipated, we aim to release the code publicly and ensure its plug-and-play functionality by November 2024. I will inform you separately at that time.

If you have any more personal requests, please feel free to contact me via email at wang-yn22@mails.tsinghua.edu.cn

With best wishes.

**Comment by heiyumiao** [comment]
Dear WangY18,

Thank you for the information! I appreciate your efforts in improving the MIM project. I'll look forward to the open-source release in November 2024. Feel free to keep me updated.

Best regards,
heiyu

**Comment by WangY18** [comment]
Hi, [heiyumiao](https://github.com/heiyumiao)! 

I have make the MIM of order $n<=3$ open source. You can plan time-optimal jerk-limited trajectories now.
